version: "2"

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  monitor:
    image: xebiafrance/trombi
    environment:
      - REDIS_HOST=redis
    labels:
      - "interlock.hostname=monitor"
      - "interlock.domain=${IP}.xip.io"
    depends_on:
      - redis
    ports:
      - 8082

  service-discovery:
    image: xebiafrance/service-discovery
    labels:
      - "interlock.hostname=service-discovery"
      - "interlock.domain=${IP}.xip.io"
    ports:
      - 8080
    environment:
        DOCKER_HOST: tcp://admin.xke-ha-swarm.aws.xebiatechevent.info:3375