version: "2"

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  monitor:
    image: xebiafrance/trombi
    environment:
      - REDIS_HOST=redis
    labels:
      - "interlock.hostname=monitor"
      - "interlock.domain=${IP}.xip.io"
    depends_on:
      - haproxy
      - redis
    ports:
      - 8082

  service-discovery:
    image: xebiafrance/service-discovery
    labels:
      - "interlock.hostname=service-discovery"
      - "interlock.domain=${IP}.xip.io"
    ports:
      - 8080
    environment:
        DOCKER_HOST: tcp://admin.xke-ha-swarm.aws.xebiatechevent.info:3375

  interlock:
    image: ehazlett/interlock:master
    command: -D run -c /etc/interlock/config.toml
    tty: true
    ports:
      - 8080
    environment:
        INTERLOCK_CONFIG: |
            ListenAddr = ":8080"
            DockerURL = "tcp://admin.xke-ha-swarm.aws.xebiatechevent.info:3375"
            [[Extensions]]
            Name = "haproxy"
            ConfigPath = "/usr/local/etc/haproxy/haproxy.cfg"
            PidPath = "/var/run/haproxy.pid"
            TemplatePath = ""
            BackendOverrideAddress = "172.17.0.1"
            MaxConn = 1024
            Port = 80
            AdminUser = "admin"
            AdminPass = "interlock"

  haproxy:
    image: haproxy:latest
    ports:
      - 80:80
    labels:
      - "interlock.ext.name=haproxy"
    environment:
      - "affinity:image==ehazlett/interlock:master"
    depends_on:
      - interlock