version: "2"

services:
  redis:
    image: redis

  monitor:
    image: xebiafrance/trombi
    environment:
      - REDIS_HOST=redis
    labels:
      - "interlock.hostname=monitor"
      - "interlock.domain=service.xke-ha-swarm.aws.xebiatechevent.info"
      - "interlock.websocket_endpoint=/ws"
    depends_on:
      - redis
    ports:
      - 8082

  service-discovery:
    image: xebiafrance/service-discovery
    labels:
      - "interlock.hostname=service-discovery"
      - "interlock.domain=service.xke-ha-swarm.aws.xebiatechevent.info"
    ports:
      - 8080
    environment:
        DOCKER_HOST: tcp://admin.xke-ha-swarm.aws.xebiatechevent.info:3375