FROM node

RUN curl https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz | tar xz -C /usr/local/
ENV PATH=$PATH:/usr/local/go/bin GOOS=linux GOARCH=amd64

WORKDIR /src
COPY package.json /src/package.json
RUN npm install

RUN mkdir /go
ENV GOPATH=/go
RUN go get github.com/gorilla/websocket
RUN go get github.com/caarlos0/env
RUN go get github.com/garyburd/redigo/redis

COPY . /src

CMD go build -o dist/trombi trombi.go && node_modules/.bin/webpack
