- name: Add Docker repository key
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: present

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
    update_cache: yes
    state: present

- name: Install (or update) docker package
  become_user: root
  apt:
    name: "docker-engine"
    state: latest
    update_cache: yes
    cache_valid_time: 600
