---

- hosts: all
  remote_user: ubuntu
  gather_facts: no
  become: yes
  become_user: root
  pre_tasks:
      - locale_gen: name=fr_FR.UTF-8 state=present
      - name: 'install python2'
        raw: apt-get -y install python-simplejson apt-transport-https ca-certificates python-pip
      - name: Install docker-py
        raw: pip install docker-py
  roles:
  - { role: docker }


- hosts: master
  remote_user: ubuntu
  tasks:
  - name: Create a consul container
    become: yes
    become_user: root
    docker_container:
      name: consul
      image: consul:v0.6.4
      command: [ "agent",  "-server" ,"-bind={{ private_ip }}","-client={{ private_ip }}" ,"-retry-join={{ hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address'] }}", "-bootstrap-expect=3" ]
      state: started
      network_mode: host
  - name: Create a swarm container
    become: yes
    become_user: root
    docker_container:
      name: swarm
      image: swarm
      command: ["manage" ,"-H", ":3375" , "--replication" , "--advertise",  "{{ private_ip }}:3375","consul://{{ private_ip }}:8500/nodes" ]
      state: started
      network_mode: host
  - name: Create an interlock proxy
    become: yes
    become_user: root
    docker_container:
      name: interlock
      image: "ehazlett/interlock:master"
      pull: yes
      command: [ '-D' , 'run' , '-c' , '/etc/interlock/config.toml' ]
      env:
        INTERLOCK_CONFIG: |
            ListenAddr = ":8080"
            DockerURL = "tcp://{{ private_ip }}:3375"

            [[Extensions]]
            Name = "haproxy"
            TemplatePath = ""
            ConfigPath= "/usr/local/etc/haproxy/haproxy.cfg"
            PidPath = "/var/run/haproxy.pid"
            BackendOverrideAddress = "172.17.0.1"
            MaxConn = 1024
            Port = 80
      ports:
        - 8080
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      tty: yes
      state: started


  - name: Create an haproxy container
    become: yes
    become_user: root
    docker_container:
      name: haproxy
      image: haproxy:latest
      ports:
        - 80:80
      labels:
        "interlock.ext.name": haproxy
      state: started
      pull: yes
      recreate: yes
      links:
        - interlock:interlock

- hosts: node
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
  - name: Create a swarm agent
    become: yes
    become_user: root
    docker_container:
      name: swarm-agent
      image: swarm
      command: ["join" , "--advertise",  "{{ private_ip }}:2375","consul://{{ hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address'] }}:8500/nodes" ]
      state: started
      network_mode: host
  - file: path="/etc/systemd/system/docker.service.d" state=directory
  - name: "Copy docker service conf"
    template: src=files/ubuntu.conf.j2 dest=/etc/systemd/system/docker.service.d/ubuntu.conf owner=root group=root mode=0644
    notify:
    - reload systemd
    - restart docker

  handlers:
  - name: reload systemd
    command: systemctl daemon-reload
  - name: restart docker
    service: name=docker state=restarted

#  roles:
#  - { role: docker }
#
#- hosts: node
#  remote_user: ubuntu