FROM golang:1.6

RUN go get github.com/gorilla/websocket
RUN go get github.com/caarlos0/env
RUN go get github.com/garyburd/redigo/redis

VOLUME $GOPATH/src/github.com/tauffredou/pcd-monitor
VOLUME /output

WORKDIR $GOPATH/src/github.com/tauffredou/pcd-monitor
CMD GOOS=linux GOARCH=amd64 go build -o /output/pcd-monitor